# baseURL = "https://example.org/"
languageCode = "zh-cn"
title = "QQY"
theme = "qqy"
paginate = 6
enableRobotsTXT = true

[markup]
  [markup.highlight]
    style = "xcode"
    lineNos = true
    lineNumbersInTable = true

[permalinks]
  posts = "/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  siteName = "QQY"
  siteTitle = "QQY.PW"
  siteSubtitle = "QQ 有 PoWer"
  author = "QQY"
  coverImage = "img/cover.svg"
  avatarUrl = "img/avatar.jpg"
  logoText = "骞"
  summaryTruncate = 200
  readingCharsPerMin = 400

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
    identifier = "home"
  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2
    identifier = "categories"
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3
    identifier = "tags"
  [[menu.main]]
    name = "归档"
    url = "/archives/"
    weight = 4
    identifier = "archives"
  [[menu.main]]
    name = "友链"
    url = "/links/"
    weight = 5
    identifier = "links"
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 6
    identifier = "about"
